sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: javaweb029
    region: cn-beijing
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxf9e9bfa5212ac85f
    secret: 2f0e56713206b1d8e0e93ff70c9ba3d7